### ISSUE TITLE
Add support for /beta version of Microsoft Graph endpoints

### ISSUE THREAD

**Issue by BrianTJackett** [microsoftgraph/msgraph-dotnet-interactive-extension#6]
Currently defaulting to /v1.0 version on Microsoft Graph.

**Comment by BrianTJackett** [comment]
Issues getting Microsoft.Graph.Beta and Microsoft.Graph NuGet packages side-by-side.  If possible, prefer to allow both versions in same extension vs. splitting to a separate extension.  Attempting instructions [here]( https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet#using-the-beta-client-along-with-the-v10-library) but unsuccessful so far.  Will reach out to Microsoft Graph .Net SDK team for assistance.

**Comment by BrianTJackett** [comment]
(disregard above mention of PR addressing issue, incorrectly tagged)

**Comment by BrianTJackett** [comment]
Able to get Beta version working but conflicts with National Cloud support as [BaseClient.BaseUrl](https://learn.microsoft.com/en-us/dotnet/api/microsoft.graph.baseclient.-ctor?view=graph-core-dotnet) is not exposed as a property to update in Beta implementation.  Checking with .Net SDK owners for follow up on why this is.

**Comment by jasonjoh** [comment]
Closed via #18
